Kaiziron

high

# Fund will be stuck in VUSD contract if the withdrawal call fails

## Summary
Funds will be stuck in VUSD contract if the withdrawal call fails in `processWithdrawals()`

## Vulnerability Detail
If the call failed, it will just emit a WithdrawalFailed event, but `start` and `i` are still incremented so the loop will never reach that withdrawal again, and VUSD tokens have already been burned in `_withdrawTo()`

## Impact
Funds will be stuck in VUSD contract and not be able to get it back

## Code Snippet
https://github.com/sherlock-audit/2023-04-hubble-exchange/blob/main/hubble-protocol/contracts/VUSD.sol#L75-L79

## Proof of concept
When the call failed to send the withdrawal amount, only an event is emitted, the failed withdrawal is not recorded, `start` and `i` are incremented and the loop will never reach that failed withdrawal in the `withdrawals` array again, so the withdrawal amount is stuck in the VUSD contract

## Tool used

Manual Review

## Recommendation
Record failed withdrawals so they can be withdrawn in the future
